"""Export utilities — AGENTS.md generation and MCP Server."""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# AGENTS.md generation
# ---------------------------------------------------------------------------

_AGENTS_MD_MAX_LINES = 60

_AGENTS_MD_HEADER = """\
# AGENTS.md — HarnessKit Skill Directory

> Auto-generated by `harnesskit export agents-md`. Do not edit manually.
> Regenerate after updating skills: `harnesskit export agents-md --output AGENTS.md`
"""

_AGENTS_MD_FOOTER = "---\n*Regenerate: `harnesskit export agents-md --output AGENTS.md`*\n"


def generate_agents_md(base: Path | None = None) -> str:
    """Generate an AGENTS.md document (≤60 lines) from registered Skills and Harnesses.

    Following the ETH Zurich research finding that AGENTS.md files exceeding 60 lines
    reduce agent performance, this function enforces a strict 60-line cap.

    Returns:
        Markdown string ready to write to AGENTS.md.
    """
    from harness_kit import skill as _skill_mod  # noqa: PLC0415
    from harness_kit import harness as _harness_mod  # noqa: PLC0415

    skills = _skill_mod.list_skills(base)
    harnesses = _harness_mod.list_harnesses(base)

    blocks: list[str] = [_AGENTS_MD_HEADER]

    # --- Skills section ---
    if skills:
        skill_lines: list[str] = ["## Skills\n"]
        for s in skills:
            name = s.get("name", "")
            desc = s.get("description", "")
            trigger = s.get("trigger", "")
            version = s.get("version", "")
            doc_path = f".harness/skills/{name}/{version}.yaml"
            if trigger:
                skill_lines.append(
                    f"- **{name}** (`{version}`): {desc}  \n"
                    f"  Trigger: _{trigger}_ | Docs: `{doc_path}`"
                )
            else:
                skill_lines.append(
                    f"- **{name}** (`{version}`): {desc} | Docs: `{doc_path}`"
                )
        blocks.append("\n".join(skill_lines) + "\n")

    # --- Harnesses section ---
    if harnesses:
        harness_lines: list[str] = ["## Harnesses\n"]
        for h in harnesses:
            name = h.get("name", "")
            desc = h.get("description", "")
            version = h.get("version", "")
            skill_refs = h.get("skills") or []
            skills_str = ", ".join(str(r) for r in skill_refs[:3])
            if len(skill_refs) > 3:
                skills_str += f" +{len(skill_refs) - 3} more"
            entry = f"- **{name}** (`{version}`): {desc}"
            if skills_str:
                entry += f"  \n  Skills: {skills_str}"
            harness_lines.append(entry)
        blocks.append("\n".join(harness_lines) + "\n")

    blocks.append(_AGENTS_MD_FOOTER)

    full_text = "\n".join(blocks)
    lines = full_text.splitlines()

    # Enforce ≤60 lines
    if len(lines) > _AGENTS_MD_MAX_LINES:
        truncated = lines[: _AGENTS_MD_MAX_LINES - 3]
        truncated += [
            "",
            "*(truncated — too many skills/harnesses to fit in 60 lines)*",
            "*Regenerate: `harnesskit export agents-md --output AGENTS.md`*",
        ]
        return "\n".join(truncated) + "\n"

    return full_text if full_text.endswith("\n") else full_text + "\n"


# ---------------------------------------------------------------------------
# MCP server
# ---------------------------------------------------------------------------


def _build_input_schema(skill_data: dict[str, Any]) -> dict[str, Any]:
    """Convert a skill's inputs list to a JSON Schema object."""
    properties: dict[str, Any] = {}
    required: list[str] = []

    for inp in skill_data.get("inputs") or []:
        prop_name = inp.get("name", "")
        if not prop_name:
            continue

        prop_type = inp.get("type", "string")
        # Map Python/HarnessKit type names to JSON Schema primitive types
        _type_map = {
            "int": "integer",
            "integer": "integer",
            "float": "number",
            "number": "number",
            "bool": "boolean",
            "boolean": "boolean",
            "array": "array",
            "list": "array",
            "object": "object",
            "dict": "object",
        }
        json_type = _type_map.get(prop_type, "string")

        prop: dict[str, Any] = {"type": json_type}
        desc = inp.get("description", "")
        if desc:
            prop["description"] = desc
        default = inp.get("default")
        if default is not None:
            prop["default"] = default

        properties[prop_name] = prop

        is_required = inp.get("required", True)
        if is_required and default is None:
            required.append(prop_name)

    schema: dict[str, Any] = {"type": "object", "properties": properties}
    if required:
        schema["required"] = required
    return schema


def build_mcp_server(base: Path | None = None) -> Any:
    """Build an MCP Server that exposes all HarnessKit Skills as MCP Tools.

    Each skill becomes a tool.  When the tool is called, the skill is invoked
    via the configured LLM (using the same pipeline as ``harnesskit skill run``).

    Args:
        base: Project root directory (must contain a ``.harness/`` directory).
              Defaults to the current working directory.

    Returns:
        An ``mcp.server.Server`` instance.

    Raises:
        ImportError: If the ``mcp`` package is not installed.
    """
    try:
        from mcp.server import Server  # noqa: PLC0415
        from mcp import types as mcp_types  # noqa: PLC0415
    except ImportError as exc:
        raise ImportError(
            "The 'mcp' package is required for MCP server support. "
            "Install it with: pip install 'harness-kit[mcp]' or pip install mcp"
        ) from exc

    from harness_kit import skill as _skill_mod  # noqa: PLC0415
    from harness_kit.config import read_config  # noqa: PLC0415
    from harness_kit.llm import LLMConfig, build_messages, call_llm  # noqa: PLC0415

    base_path = base

    server = Server("harnesskit")

    @server.list_tools()
    async def handle_list_tools() -> list[mcp_types.Tool]:  # type: ignore[misc]
        """Return all registered Skills as MCP Tool definitions."""
        tools: list[mcp_types.Tool] = []
        for s in _skill_mod.list_skills(base_path):
            tools.append(
                mcp_types.Tool(
                    name=s["name"],
                    description=s.get("description", ""),
                    inputSchema=_build_input_schema(s),
                )
            )
        return tools

    @server.call_tool()
    async def handle_call_tool(  # type: ignore[misc]
        name: str,
        arguments: dict[str, Any] | None,
    ) -> list[mcp_types.TextContent | mcp_types.ImageContent | mcp_types.EmbeddedResource]:
        """Invoke a HarnessKit Skill and return its output as TextContent."""
        args: dict[str, Any] = arguments or {}

        # Load skill
        try:
            skill_data = _skill_mod.load_skill(name, base=base_path)
        except FileNotFoundError:
            return [mcp_types.TextContent(type="text", text=f"Skill '{name}' not found.")]

        # Fill defaults
        vars_dict: dict[str, str] = {k: str(v) for k, v in args.items()}
        for inp in skill_data.get("inputs") or []:
            inp_name = inp.get("name", "")
            if inp_name not in vars_dict and inp.get("default") is not None:
                vars_dict[inp_name] = str(inp["default"])

        # Render skill prompt assets
        try:
            rendered = _skill_mod.render_skill_prompt(name, base=base_path)
        except Exception as exc:
            return [mcp_types.TextContent(type="text", text=f"Failed to render skill: {exc}")]

        # Build LLM config
        try:
            cfg = read_config(base=base_path)
        except Exception:
            cfg = {}
        llm_config = LLMConfig.from_harness_config(cfg)

        # Build messages and call LLM (synchronous call in a thread)
        messages = build_messages(skill_data, rendered, vars_dict)
        try:
            loop = asyncio.get_event_loop()
            resp = await loop.run_in_executor(
                None, lambda: call_llm(messages, llm_config, stream=False)
            )
        except Exception as exc:
            return [mcp_types.TextContent(type="text", text=f"LLM call failed: {exc}")]

        output = resp.content  # type: ignore[union-attr]
        return [mcp_types.TextContent(type="text", text=output)]

    return server


async def _run_mcp_stdio(base: Path | None = None) -> None:
    """Run the MCP server over stdio (standard transport for Claude Desktop / Cursor)."""
    try:
        from mcp.server.stdio import stdio_server  # noqa: PLC0415
    except ImportError as exc:
        raise ImportError(
            "The 'mcp' package is required. "
            "Install with: pip install 'harness-kit[mcp]' or pip install mcp"
        ) from exc

    server = build_mcp_server(base)
    init_options = server.create_initialization_options()
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, init_options)


def run_mcp_server(base: Path | None = None) -> None:
    """Entry point: start the MCP stdio server (blocking).

    This is the function called by ``harnesskit export mcp``.
    """
    asyncio.run(_run_mcp_stdio(base))
